### ISSUE TITLE
use dataclasses-json to deserialize responses into well-formed objects

### ISSUE THREAD

**Issue by sumnerevans** [sumnerevans/linkedin-matrix#13]
https://github.com/lidatong/dataclasses-json/

I have used this successfully in Sublime Music: https://gitlab.com/sublime-music/sublime-music/-/blob/master/sublime_music/adapters/subsonic/api_objects.py

It should help avoid awkward `.get` chains on the JSON dictionaries that are returned.

**Comment by sumnerevans** [comment]
Maybe actually should just modify `linkedin-api` to do this?

**Comment by tulir** [comment]
mautrix-python also has a system for this: https://github.com/tulir/mautrix-python/tree/master/mautrix/types

**Comment by sumnerevans** [comment]
This is done now that I've migrated to https://github.com/sumnerevans/linkedin-messaging-api
